### PR TITLE
add unison-diy

### PR DESCRIPTION
**Pull request by tagirb**
This directory provides an example of building a 'do-it-yourself'
synchronization container for macOS (aka Darwin). Linux compatibility is
also provided.

### CODE REVIEW

**Comment by EugenMayer** [comment]
just curious - why should someone would want to do that?

**Comment by tagirb** [comment]
Hi Eugen, first of all, thanks for the `docker-sync` that served as a great starting point. It just seemed to be too generic for our project -- we only needed to sync one directory. So I basically ripped out the unison part and integrated it in our project as a plain docker-compose file + a custom Dockerfile for building the unison container. It was just enough.

So, the motivation is:
- extremely simple and stripped down: easy to understand, customize and integrate
- no external dependencies, plain docker / docker-compose
- portability: runs on both macOS and Linux

**Comment by EugenMayer** [comment]
I understand - so you removed any usages of docker-sync - if that suits you, that is great.

But why should this be part of **docker-sync**-boilerplate?

**Comment by tagirb** [comment]
Why not? `docker-sync` seems to be quite popular, so I thought it makes more sense to publish this tiny example here, than publishing it as a separate project. Will also help people to understand what `docker-sync` is actually doing.

**Comment by EugenMayer** [comment]
sorry, this just does not make any sense. Neither you included your project and this all is by any means "buildable", nor it is a docker-sync based implementation as a different ( unison-simple ) strategy.

Its a broken ( not buildable ) non related, specific implementation of one team and would just confuse people.

**Comment by EugenMayer** [comment]
sorry, just seen the dockerfile - so its buildable, but still massively unrelated. I am not going to confuse people with even more options which do not even relate to docker-sync ( its enought with docker-sync alone already )

**Comment by tagirb** [comment]
Ok, cool, thanks for the feedback.

**Pull request closed without merging**
